#version: "3"
#services:
#  mystore:
#    image: german1982/my-store
#    networks:
#      - mystore-network
#
#    redis:
#      image: "redis:alpine"
#  command: [ "redis-server", "--protected-mode", "no" ]
#  ports:
#    - "6379:6379"
#    networks:
#      - mystore-network
#
#networks:
#  mystore-network:
#

#version: '2'
#services:
#  my-store:
#    image: my-store
#    ports:
#      - "8080:8080"
#    links:
#      - "db:redis"
#  db:
#    image: "redis:alpine"
#    hostname: redis
#    ports:
#      - "6379:6379"

#version: '3'
#services:
#  store:
#    #image: german1982/my-store
#    image: my-store
#    ports:
#      - "8080:8080"
#    networks:
#      - consumer-producer
#  redis:
#    #image: redis
#    image: "redis:alpine"
#    command: [ "redis-server", "--protected-mode", "no" ]
#    ports:
#      - "6379:6379"
#    networks:
#      - consumer-producer
#
#networks:
#  consumer-producer:
#    #external: true


version: '2'
services:
  app:
    #build: .
#    image: german1982/my-store
    image: my-store
    ports:
      - "8080:8080"
    links:
      - "db:redis"
    depends_on:
      - db
  db:
    image: "redis:alpine"
    command: [ "redis-server", "--protected-mode", "no" ]
    hostname: localhost
    ports:
      - "6379:6379"