version: '3'
services:
  app:
    image: german1982/my-store
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - mystore-network
  redis:
    image: "redis:alpine"
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
    networks:
      - mystore-network

  my-client:
    container_name: my-client
    image: german1982/my-client
#    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    networks:
      - mystore-network
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    networks:
      - mystore-network

networks:
  mystore-network:




#####################################################################
#                USING LINK VERSION!!
#version: '2'
#services:
#  app:
#    #build: .
##    image: german1982/my-store
#    image: my-store
#    ports:
#      - "8080:8080"
#    links:
#      - "db:redis"
#    depends_on:
#      - db
#  db:
#    image: "redis:alpine"
#    command: [ "redis-server", "--protected-mode", "no" ]
#    hostname: localhost
#    ports:
#      - "6379:6379"
#####################################################################

